# Use the latest foundry image
FROM ghcr.io/foundry-rs/foundry

WORKDIR /app
COPY . .

ARG mnemonic
ARG infura_url
ENV mnemonic=$mnemonic
ENV infura_url=$infura_url

RUN forge build
EXPOSE 8545/udp
EXPOSE 8545/tcp
ENTRYPOINT anvil -m "$mnemonic" --fork-url $infura_url --no-cors --host 0.0.0.0
