[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[etherscan]
polygon = { key = "EII3M4G2MKTHAS6METKBJH149P8EFWV9ZP", url = "https://api.polygonscan.com/api" }
bsc = { key = "B2JV9AVIVIWWDFDCB27KR1NJ35QEWS552H", url = "https://api.bscscan.com/api" }
optimism = { key = "BPHPNQ1IYRT2FFUPIWQXN2Z7YY1P3IGCXN", url = "https://api-optimistic.etherscan.io/api" }
blast = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/168587773/etherscan" }
arbitrum = { key = "X87MF2WYWNXBI2AE3ZZNADUXC5E15A7SW4", url = "https://api.arbiscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config